permalink   : /:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

baseurl: "" # change to empty string ""
domain_name: educostachaves.github.io
google_analytics: UA-70437282-1

source:      source
destination: _site

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: Eduardo Chaves
title: Eduardo Chaves | Front End and Web Developer
description: "Front-End, FullStack, Designer and Web Developer"
meta_description: "Front-End, FullStack, Designer and Web Developer"
meta_keywords: "website, webdeveloper, front end, front end develper, website, e-commerce, wordpress, frontend, front-end, html5, css3, javascript, jquery, seo, performance, react, flux, relay, graphql"
url: http://educostachaves.github.io
production_url: http://educostachaves.github.io
repo: https://github.com/educostachaves/educostachaves.github.io
disqus_shortname: "educostachaves"
rss_path: source/
author:
  name      : Eduardo Chaves
  image     : /assets/images/perfil.jpg
  email     : educostachaves@gmail.com
  url       : http://educostachaves.github.io
  facebook  : http://facebook.com/educostachaves
  twitter   : http://twitter.com/educostachaves
  instagram : http://instagram.com/educostachaves
  github    : http://github.com/educostachaves
  linkedin  : http://linkedin.com/in/educostachaves
  bio       : "Desenvolvedor Front-end/Wordpress entusiasta de performance, design responsivo e usabilidade, sempre em busca do melhor projeto e de um bom café."

# thought
thought:
  text: I have no special talent. I am only passionately curious.
  author: Albert Einstein

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/ # change to /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
