# Site settings
title: Eduardo Chaves
email: educostachaves@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing cool stuff to learn more front-end features.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eduardochaves.com.br/" # the base hostname & protocol for your site
twitter_username: educostachaves
github_username:  educostachaves

# Build settings
markdown: kramdown
